/**
 * AICVBuilder.jsx
 *
 * HOW THE API CALL WORKS
 * ─────────────────────────────────────────────────────────────────────────────
 * The CV is generated by calling the Anthropic Messages API directly from the
 * browser, using the key stored in import.meta.env.VITE_ANTHROPIC_API_KEY.
 *
 * ⚠  PRODUCTION NOTE: exposing API keys in client-side code is insecure.
 *    In production, proxy the call through your own backend:
 *      POST /api/generate-cv  → server calls Anthropic → returns text.
 *    Replace generateCV() below with a call to your proxy endpoint.
 *
 * HOW TO PLUG IN
 * • Create a .env file in the project root:
 *     VITE_ANTHROPIC_API_KEY=sk-ant-...
 * • Run `npm run dev` — the key is injected at build time.
 */

import { useState } from 'react'

// ─── Constants ─────────────────────────────────────────────────────────────────
const POSITIONS_LIST = [
  'Goalkeeper', 'Centre-Back', 'Right-Back', 'Left-Back',
  'Defensive Midfielder', 'Central Midfielder', 'Attacking Midfielder',
  'Right Winger', 'Left Winger', 'Striker',
]

const INITIAL_FORM = {
  name:          '',
  age:           '',
  positions:     [],     // string[]
  preferredFoot: 'Right',
  height:        '',
  currentClub:   '',
  previousClubs: '',
  appearances:   '',
  goals:         '',
  assists:       '',
  cleanSheets:   '',
  achievements:  '',
  bio:           '',
}

// ─── API call ──────────────────────────────────────────────────────────────────
function buildPrompt(f) {
  const isGK = f.positions.includes('Goalkeeper')
  return `You are an expert football CV writer. Create a polished, professional football CV for the following player:

NAME: ${f.name}
AGE: ${f.age}
POSITION(S): ${f.positions.join(', ') || 'Not specified'}
PREFERRED FOOT: ${f.preferredFoot}
HEIGHT: ${f.height || 'Not provided'}

CAREER HISTORY:
Current Club: ${f.currentClub || 'Not specified'}
Previous Clubs: ${f.previousClubs || 'None listed'}

KEY STATISTICS:
Appearances: ${f.appearances || '—'}
Goals: ${f.goals || '—'}
Assists: ${f.assists || '—'}${isGK || f.cleanSheets ? `\nClean Sheets: ${f.cleanSheets || '—'}` : ''}

ACHIEVEMENTS & HONOURS:
${f.achievements || 'None listed'}

PLAYER'S OWN WORDS:
"${f.bio || 'Not provided'}"

Format the CV EXACTLY as follows — use plain text, no markdown symbols:

═══════════════════════════════════════════════════════════
${(f.name || 'PLAYER NAME').toUpperCase()} — FOOTBALL CV
${(f.positions[0] || 'Position').toUpperCase()} | Preferred Foot: ${f.preferredFoot} | Height: ${f.height || 'N/A'}
═══════════════════════════════════════════════════════════

PROFILE SUMMARY
[3–4 compelling sentences. Sell the player's style, key strengths, and ambition. Mention specific technical or physical attributes implied by their position and stats.]

PLAYING ATTRIBUTES
• [List 7–9 key playing attributes as bullet points relevant to their position(s)]

CAREER HISTORY
[List each club from most recent to oldest. One or two sentences per club describing their contribution, role, and development.]

KEY STATISTICS
[Formatted stats — appearances, goals, assists${isGK ? ', clean sheets' : ''}. Add any inferred context.]

ACHIEVEMENTS & HONOURS
[Bullet list based on the achievements provided. If none, suggest likely milestones for their level.]

Tone: confident and professional. Appropriate for a player seeking opportunities at semi-professional or professional academy level.`
}

async function generateCV(formData) {
  const key = import.meta.env.VITE_ANTHROPIC_API_KEY
  if (!key) throw new Error('NO_KEY')

  const res = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-api-key': key,
      'anthropic-version': '2023-06-01',
    },
    body: JSON.stringify({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 1600,
      messages: [{ role: 'user', content: buildPrompt(formData) }],
    }),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || `API error ${res.status}`)
  }

  const data = await res.json()
  return data.content[0].text
}

// ─── Sub-components ────────────────────────────────────────────────────────────
function PositionPicker({ selected, onChange }) {
  const toggle = (pos) =>
    onChange(
      selected.includes(pos)
        ? selected.filter(p => p !== pos)
        : [...selected, pos],
    )

  return (
    <div className="position-picker" role="group" aria-label="Select your positions">
      {POSITIONS_LIST.map(pos => (
        <button
          key={pos}
          type="button"
          className={`position-pill${selected.includes(pos) ? ' active' : ''}`}
          onClick={() => toggle(pos)}
          aria-pressed={selected.includes(pos)}
        >
          {pos}
        </button>
      ))}
    </div>
  )
}

function CVOutput({ cv, onRegenerate, loading }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = async () => {
    await navigator.clipboard.writeText(cv)
    setCopied(true)
    setTimeout(() => setCopied(false), 2500)
  }

  return (
    <div className="cv-output">
      <div className="cv-output__toolbar">
        <h3 className="cv-output__heading">Your Generated CV</h3>
        <div className="cv-output__actions">
          <button type="button" className="cv-btn cv-btn--outline" onClick={handleCopy} disabled={loading}>
            {copied ? '✓ Copied!' : 'Copy text'}
          </button>
          <button type="button" className="cv-btn cv-btn--primary" onClick={onRegenerate} disabled={loading}>
            {loading ? 'Regenerating…' : 'Regenerate'}
          </button>
        </div>
      </div>
      <pre className="cv-output__text" aria-live="polite" aria-label="Generated CV text">
        {cv}
      </pre>
    </div>
  )
}

// ─── Main component ────────────────────────────────────────────────────────────
export default function AICVBuilder() {
  const [form, setForm]         = useState(INITIAL_FORM)
  const [cv, setCV]             = useState('')
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState('')
  const [submitted, setSubmitted] = useState(false)

  const set = key => e => setForm(f => ({ ...f, [key]: e.target.value }))
  const setPositions = positions => setForm(f => ({ ...f, positions }))

  const isGoalkeeper = form.positions.includes('Goalkeeper')

  const validate = () => {
    if (!form.name.trim())         return 'Please enter your name.'
    if (!form.age || +form.age < 14 || +form.age > 40) return 'Please enter a valid age (14–40).'
    if (form.positions.length === 0) return 'Please select at least one position.'
    if (!form.currentClub.trim())  return 'Please enter your current or most recent club.'
    return null
  }

  const handleSubmit = async e => {
    e.preventDefault()
    const err = validate()
    if (err) { setError(err); return }
    setError('')
    setLoading(true)
    setSubmitted(true)
    try {
      const result = await generateCV(form)
      setCV(result)
    } catch (ex) {
      if (ex.message === 'NO_KEY') {
        setError('No API key found. Add VITE_ANTHROPIC_API_KEY to your .env file to enable the AI CV builder.')
      } else {
        setError(`Something went wrong: ${ex.message}. Please try again.`)
      }
      setSubmitted(false)
    } finally {
      setLoading(false)
    }
  }

  const handleRegenerate = async () => {
    setError('')
    setLoading(true)
    try {
      const result = await generateCV(form)
      setCV(result)
    } catch (ex) {
      setError(`Regeneration failed: ${ex.message}`)
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="cv-builder">
      <div className={`cv-builder__layout${cv ? ' cv-builder__layout--split' : ''}`}>

        {/* ── Form ── */}
        <form
          className="cv-builder__form"
          onSubmit={handleSubmit}
          noValidate
          aria-label="Football CV builder form"
        >
          {error && (
            <div className="form-error" role="alert">{error}</div>
          )}

          {/* Row 1: name + age */}
          <div className="cv-form-row">
            <div className="form-group">
              <label className="form-label" htmlFor="cv-name">Full name <span aria-hidden="true">*</span></label>
              <input id="cv-name" type="text" className="form-input" value={form.name}
                onChange={set('name')} placeholder="Your full name" autoComplete="name" required />
            </div>
            <div className="form-group cv-form-row__narrow">
              <label className="form-label" htmlFor="cv-age">Age <span aria-hidden="true">*</span></label>
              <input id="cv-age" type="number" className="form-input" value={form.age}
                onChange={set('age')} placeholder="e.g. 19" min={14} max={40} required />
            </div>
          </div>

          {/* Position picker */}
          <div className="form-group">
            <span className="form-label" id="pos-label">
              Position(s) <span aria-hidden="true">*</span>
            </span>
            <PositionPicker selected={form.positions} onChange={setPositions} />
          </div>

          {/* Row 2: foot + height */}
          <div className="cv-form-row">
            <div className="form-group">
              <label className="form-label" htmlFor="cv-foot">Preferred foot</label>
              <select id="cv-foot" className="form-input form-select" value={form.preferredFoot} onChange={set('preferredFoot')}>
                <option>Right</option>
                <option>Left</option>
                <option>Both</option>
              </select>
            </div>
            <div className="form-group">
              <label className="form-label" htmlFor="cv-height">Height</label>
              <input id="cv-height" type="text" className="form-input" value={form.height}
                onChange={set('height')} placeholder="e.g. 5'11 / 180cm" />
            </div>
          </div>

          {/* Clubs */}
          <div className="form-group">
            <label className="form-label" htmlFor="cv-current-club">
              Current / most recent club <span aria-hidden="true">*</span>
            </label>
            <input id="cv-current-club" type="text" className="form-input" value={form.currentClub}
              onChange={set('currentClub')} placeholder="e.g. Hyde United FC" required />
          </div>

          <div className="form-group">
            <label className="form-label" htmlFor="cv-prev-clubs">Previous clubs</label>
            <textarea id="cv-prev-clubs" className="form-input form-textarea" value={form.previousClubs}
              onChange={set('previousClubs')} placeholder="List each club on a new line, e.g.&#10;Radcliffe FC (2023–24)&#10;Bamber Bridge FC (2022–23)" rows={3} />
          </div>

          {/* Stats */}
          <fieldset className="cv-stats-fieldset">
            <legend className="form-label">Key statistics</legend>
            <div className="cv-stats-grid">
              <div className="form-group">
                <label className="form-label" htmlFor="cv-apps">Appearances</label>
                <input id="cv-apps" type="number" className="form-input" value={form.appearances}
                  onChange={set('appearances')} placeholder="e.g. 42" min={0} />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="cv-goals">Goals</label>
                <input id="cv-goals" type="number" className="form-input" value={form.goals}
                  onChange={set('goals')} placeholder="e.g. 14" min={0} />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="cv-assists">Assists</label>
                <input id="cv-assists" type="number" className="form-input" value={form.assists}
                  onChange={set('assists')} placeholder="e.g. 9" min={0} />
              </div>
              {(isGoalkeeper || form.cleanSheets) && (
                <div className="form-group">
                  <label className="form-label" htmlFor="cv-cs">Clean sheets</label>
                  <input id="cv-cs" type="number" className="form-input" value={form.cleanSheets}
                    onChange={set('cleanSheets')} placeholder="e.g. 11" min={0} />
                </div>
              )}
            </div>
          </fieldset>

          {/* Achievements */}
          <div className="form-group">
            <label className="form-label" htmlFor="cv-achievements">Achievements &amp; honours</label>
            <textarea id="cv-achievements" className="form-input form-textarea" value={form.achievements}
              onChange={set('achievements')} placeholder="e.g. Top scorer 2024/25, Player of the Year, County Cup winner" rows={3} />
          </div>

          {/* Bio */}
          <div className="form-group">
            <label className="form-label" htmlFor="cv-bio">In your own words (optional)</label>
            <textarea id="cv-bio" className="form-input form-textarea" value={form.bio}
              onChange={set('bio')} placeholder="A short description of your playing style, mentality, and ambitions…" rows={4} />
          </div>

          <button
            type="submit"
            className="form-submit cv-builder__submit"
            disabled={loading}
            aria-describedby={error ? 'cv-error' : undefined}
          >
            {loading ? (
              <><span className="spinner" aria-hidden="true" /> Generating your CV…</>
            ) : (
              '✨ Generate my football CV'
            )}
          </button>

          {!import.meta.env.VITE_ANTHROPIC_API_KEY && !submitted && (
            <p className="cv-builder__key-hint">
              Add <code>VITE_ANTHROPIC_API_KEY</code> to your <code>.env</code> file to enable CV generation.
            </p>
          )}
        </form>

        {/* ── Output ── */}
        {(cv || (loading && submitted)) && (
          <div className="cv-output-wrap">
            {loading && !cv ? (
              <div className="cv-output cv-output--loading" aria-live="polite" aria-busy="true">
                <div className="cv-loading">
                  <div className="cv-loading__dots" aria-hidden="true">
                    <span /><span /><span />
                  </div>
                  <p className="cv-loading__text">Crafting your CV…</p>
                </div>
              </div>
            ) : cv ? (
              <CVOutput cv={cv} onRegenerate={handleRegenerate} loading={loading} />
            ) : null}
          </div>
        )}
      </div>
    </div>
  )
}
